# escape=`
FROM microsoft/nanoserver:10.0.14393.1593

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" `
  org.label-schema.name="Gopad UI" `
  org.label-schema.vendor="Thomas Boerger" `
  org.label-schema.schema-version="1.0"

EXPOSE 9000 80 443
VOLUME c:\storage

ENV UMSCHLAG_UI_ASSETS c:\assets
ENV UMSCHLAG_UI_STORAGE c:\storage

ENTRYPOINT ["c:\gopad-ui.exe"]
CMD ["server"]

COPY dist/static c:\assets
COPY gopad-ui.exe c:\gopad-ui.exe
