FROM arm32v6/alpine:3.15
RUN apk add --no-cache ca-certificates mailcap

EXPOSE 8000 8080
ENTRYPOINT ["/usr/bin/gopad-ui"]
CMD ["server"]

ENV GOPAD_UI_ASSETS /usr/share/gopad

COPY dist/static /usr/share/gopad
COPY dist/binaries/gopad-ui /usr/bin/gopad-ui
