FROM i386/alpine:3.20

RUN apk add --no-cache ca-certificates mailcap && \
    addgroup -g 1337 gopad && \
    adduser -D -u 1337 -h /var/lib/gopad -G gopad gopad

EXPOSE 8000 8080
ENTRYPOINT ["/usr/bin/gopad-ui"]
CMD ["server"]

COPY --chown=1337:1337 static /usr/share/gopad
COPY bin/gopad-ui /usr/bin/gopad-ui
WORKDIR /var/lib/gopad
USER gopad
