FROM amd64/alpine:3.19
RUN apk add --no-cache ca-certificates mailcap

EXPOSE 8000 8080
ENTRYPOINT ["/usr/bin/gopad-ui"]
CMD ["server"]

ENV GOPAD_UI_ASSETS /usr/share/gopad

COPY static /usr/share/gopad
COPY bin/gopad-ui /usr/bin/gopad-ui
